# -*- coding: utf-8 -*-
"""ASED LAB FULL stack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nE6mDKgLokxQOYPkw5438KG7wDbhuA1K

---
"""

#import modules
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn import model_selection
from sklearn import linear_model

X=[[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0],[20.0]]
Y=[8,10,12,14,16,18,20]
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X,Y,test_size=0.3,random_state=7)
print("Trining Features",X_train);print("Training Labels",Y_train)
print("Testing Features",X_test);print("Testing Labels",Y_test)
reg=linear_model.LinearRegression()
reg.fit(X_train,Y_train)
#accuracy on test set
result = reg.score(X_test, Y_test)
print("Accuracy:-test set: %.2f%%" % (result*100.0))
X_height=[[12.0]]
print(reg.predict(X_test))



