# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb
"""


import qiskit
import qiskit_aer

print("Qiskit version:", qiskit.__version__)
print("Aer working!")

# ============================
# IMPORTS
# ============================
import pandas as pd
import numpy as np

from qiskit_aer import Aer
from qiskit.circuit.library import ZZFeatureMap, TwoLocal
from qiskit_machine_learning.algorithms import VQC

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# ============================
# SEED
# ============================
np.random.seed(1376)

# ============================
# LOAD DATA
# ============================
df = pd.read_csv('Iris.csv')

if 'Id' in df.columns:
    df = df.drop(columns=['Id'])

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# ============================
# ENCODE LABELS
# ============================
le = LabelEncoder()
y = le.fit_transform(y)

# ✅ ONE-HOT ENCODING (IMPORTANT)
y = np.eye(len(np.unique(y)))[y]

# ============================
# SCALE DATA
# ============================
scaler = StandardScaler()
X = scaler.fit_transform(X)

from sklearn.decomposition import PCA

# ============================
# SCALE DATA
# ============================
scaler = StandardScaler()
X = scaler.fit_transform(X)

# ✅ Use PCA instead of slicing
pca = PCA(n_components=2)
X = pca.fit_transform(X)

# ============================
# SPLIT
# ============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
# ============================
# BACKEND
# ============================
backend = Aer.get_backend('aer_simulator')

# ============================
# CIRCUITS
# ============================
feature_map = ZZFeatureMap(2, reps=2)
ansatz = TwoLocal(2, ['ry', 'rz'], 'cz', reps=4)

# ============================
# MODEL
# ============================
from qiskit_algorithms.optimizers import COBYLA

vqc = VQC(
    feature_map=feature_map,
    ansatz=ansatz,
    optimizer=COBYLA(maxiter=200)
)

# ============================
# TRAIN
# ============================
vqc.fit(X_train, y_train)

# ============================
# TEST
# ============================
accuracy = vqc.score(X_test, y_test)
print(f"Testing accuracy: {accuracy:.2f}")

from sklearn.svm import SVC

# Convert one-hot back to labels
y_train_classical = np.argmax(y_train, axis=1)
y_test_classical = np.argmax(y_test, axis=1)

model = SVC()
model.fit(X_train, y_train_classical)

classical_acc = model.score(X_test, y_test_classical)
print(f"Classical Accuracy: {classical_acc:.2f}")

# ============================
# IMPORTS
# ============================
import numpy as np

from qiskit.circuit.library import ZZFeatureMap, TwoLocal, RealAmplitudes
from qiskit_machine_learning.algorithms import VQC
from qiskit_machine_learning.datasets import ad_hoc_data

# ============================
# SEED
# ============================
np.random.seed(1376)

# ============================
# DATASET
# ============================
feature_dim = 2
training_size = 20
test_size = 10

training_features, training_labels, test_features, test_labels = ad_hoc_data(
    training_size=training_size,
    test_size=test_size,
    n=feature_dim,
    gap=0.3
)

# ============================
# MODEL 1
# ============================
print("\n--- Model 1 ---")

feature_map = ZZFeatureMap(feature_dimension=feature_dim, reps=2)
ansatz = TwoLocal(2, ['ry', 'rz'], 'cz', reps=3)

vqc = VQC(
    feature_map=feature_map,
    ansatz=ansatz
)

# Train
vqc.fit(training_features, training_labels)

# Test
score = vqc.score(test_features, test_labels)
print(f"Testing accuracy (Model 1): {score:.2f}")

# ============================
# MODEL 2 (Simpler Ansatz)
# ============================
print("\n--- Model 2 ---")

X_train, y_train, X_test, y_test = ad_hoc_data(
    training_size=20,
    test_size=10,
    n=2,
    gap=0.1
)

feature_map2 = ZZFeatureMap(2)
ansatz2 = RealAmplitudes(2, reps=1)

vqc2 = VQC(
    feature_map=feature_map2,
    ansatz=ansatz2
)

# Train
vqc2.fit(X_train, y_train)

# Test
score2 = vqc2.score(X_test, y_test)
print(f"Testing accuracy (Model 2): {score2:.2f}")

# ============================
# DONE
# ============================
print("\nExecution completed successfully!")

